### ISSUE TITLE
Print "hello open source" in Java

### ISSUE THREAD

**Issue by AnnuJoshi** [AnnuJoshi/github102-algorithms#2]
### Instructions

1. Create a new java file `hello_open_source_in_java.java` 
2. Add code to print hello open source

**Comment by prasidh-agg** [comment]
Have raised PR for this, it's my first ever open source issue.

**Comment by AnnuJoshi** [comment]
Thank you @prasidh-agg  congratulation on solving your first issue 👍

**Comment by prasidh-agg** [comment]
Thankyou so much 😀
